name: vietnambeyondthehorizon
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  location: ^8.0.1
  http: ^1.5.0
  flutter_polyline_points: ^3.1.0
  polyline_codec: ^0.1.6
  flutter_compass: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans/InriaSans-Regular.ttf
        - asset: assets/fonts/InriaSans/InriaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InriaSans/InriaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/InriaSans/InriaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/InriaSans/InriaSans-Light.ttf
          weight: 200
        - asset: assets/fonts/InriaSans/InriaSans-LightItalic.ttf
          weight: 200
          style: italic
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/Jost-Black.ttf
          weight: 900
        - asset: assets/fonts/Jost/Jost-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Jost/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost/Jost-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Jost/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jost/Jost-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Jost/Jost-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Jost/Jost-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Jost/Jost-Italic.ttf
          style: italic
        - asset: assets/fonts/Jost/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost/Jost-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost/Jost-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Jost/Jost-Regular.ttf
        - asset: assets/fonts/Jost/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost/Jost-SemiBold.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Jost/Jost-Thin.ttf
          weight: 100
        - asset: assets/fonts/Jost/Jost-Thin.ttf
          weight: 100
          style: italic
    - family: KronaOne
      fonts:
        - asset: assets/fonts/KronaOne/KronaOne-Regular.ttf
    - family: Inder
      fonts:
        - asset: assets/fonts/Inder/Inder-Regular.ttf
  assets:
    - assets/icons/camera-icon.png
    - assets/icons/diamond-icon.png
    - assets/icons/gamepad.png
    - assets/icons/home.png
    - assets/icons/ranking-star.png
    - assets/icons/heart.png
    - assets/icons/user.png
    - assets/icons/star.png
    - assets/icons/bar.png
    - assets/temporary/lorem_ipsum_background.png