// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8MYw9spPtE1HdOVOTB5jgxWAZfR5R508',
    appId: '1:419875383273:web:4500c2ef682f3c2d47cd78',
    messagingSenderId: '419875383273',
    projectId: 'vietnam-beyond-the-horizon',
    authDomain: 'vietnam-beyond-the-horizon.firebaseapp.com',
    storageBucket: 'vietnam-beyond-the-horizon.firebasestorage.app',
    measurementId: 'G-BZZ3J9Z31D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiKfUsIDQX-QVjy-ao0IK21s7tWy0yEm4',
    appId: '1:419875383273:android:1f6921151166c4b247cd78',
    messagingSenderId: '419875383273',
    projectId: 'vietnam-beyond-the-horizon',
    storageBucket: 'vietnam-beyond-the-horizon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtv7eGTxDVo050LpDUCV6_w9dFk0otcg',
    appId: '1:419875383273:ios:49309dc0e6a8a5f447cd78',
    messagingSenderId: '419875383273',
    projectId: 'vietnam-beyond-the-horizon',
    storageBucket: 'vietnam-beyond-the-horizon.firebasestorage.app',
    iosBundleId: 'com.example.vietnambeyondthehorizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtv7eGTxDVo050LpDUCV6_w9dFk0otcg',
    appId: '1:419875383273:ios:49309dc0e6a8a5f447cd78',
    messagingSenderId: '419875383273',
    projectId: 'vietnam-beyond-the-horizon',
    storageBucket: 'vietnam-beyond-the-horizon.firebasestorage.app',
    iosBundleId: 'com.example.vietnambeyondthehorizon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8MYw9spPtE1HdOVOTB5jgxWAZfR5R508',
    appId: '1:419875383273:web:9d54f8e795ea51ea47cd78',
    messagingSenderId: '419875383273',
    projectId: 'vietnam-beyond-the-horizon',
    authDomain: 'vietnam-beyond-the-horizon.firebaseapp.com',
    storageBucket: 'vietnam-beyond-the-horizon.firebasestorage.app',
    measurementId: 'G-8WP36636Q9',
  );
}
